name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: unbuntu-latest

    steps:

      - uses: actions/checkout@v4.2.1
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secret.DOCKERUSER}}
          password: ${{ secret.PASSWORD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
           context: .
           file: .
           push: true
           tags: |
             laranjeirajuliano/online-store:1.1.0
             laranjeirajuliano/online-store:latest
        
