name: CI

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKERUSER: ${{ secrets.DOCKERUSER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SHORT_SHA: ${{ github.sha }}[:5]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: backend-storage:${{ env.SHORT_SHA }}

      - name: Install Dive
        run: |
          DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb
          sudo apt install ./dive_${DIVE_VERSION}_linux_amd64.deb

      - name: Install Docker-Squash
        run: |
          sudo apt install pipx
          pipx install docker-squash

      - name: Squash Image
        run: |
          docker-squash -t laranjeirajuliano/online-store:latest backend-storage:${{ env.SHORT_SHA }}

      - name: Tag Latest
        run: |
          docker tag laranjeirajuliano/online-store:${{ env.SHORT_SHA }} laranjeirajuliano/online-store:latest

      - name: Dive Inspection
        run: |
          CI=true dive ${{ secrets.DOCKERUSER }}/online-store:${{ env.SHORT_SHA }}

      - name: Push Image
        run: |
          docker push laranjeirajuliano/online-store:${{ env.SHORT_SHA }}
          docker push laranjeirajuliano/online-store:latest
