name: CI

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-l atest
    env:
      DOCKERUSER: ${{ secrets.DOCKERUSER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SHORT_SHA: ${{ github.sha }}[:5]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.PASSWORD }}

      - name: Install Dive
        run: |
          DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb
          sudo apt install ./dive_${DIVE_VERSION}_linux_amd64.deb

      - name: Install Docker-Squash
        run: |
          sudo apt install pipx
          pipx install docker-squash

      - name: Squash Image
        run: |
          docker-squash -t my-squashed-image:latest .

      - name: Tag Latest
        run: |
          docker tag my-squashed-imag:latest ${{ secrets.DOCKERUSER }}/online-store:${{ env.SHORT_SHA }}

      - name: Dive Inspection
        run: |
          CI=true dive ${{ secrets.DOCKERUSER }}/online-store:${{ env.SHORT_SHA }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERUSER }}/online-store:${{ env.SHORT_SHA }}
