name: CI with SemVer and Conventional Commits

on:
  push:
    branches: [main]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKERUSER }}
  DOCKER_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.PASSWORD }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "GH_TOKEN: $GH_TOKEN"
          echo "NPM_TOKEN: $NPM_TOKEN"
          npx semantic-release

      - name: Build and push Docker images
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERUSER }}/online-store:${{ steps.semantic_release.outputs.version }}
            ${{ secrets.DOCKERUSER }}/online-store:latest

      - name: Create a Git tag
        run: |
          echo "Creating tag: v${{ steps.semantic_release.outputs.version }}"

          git tag -f v${{ steps.semantic_release.outputs.version }}

          echo "Tag created: $(git tag -l)"

          echo "Pushing tag: v${{ steps.semantic_release.outputs.version }}"

          git push origin v${{ steps.semantic_release.outputs.version }} --force || {

            echo "Error pushing tag: $?"

            exit 1

          }
